import './global.css';
import React from "react";
import { Toaster } from 'react-hot-toast';

export const metadata = {
  title: 'Welcome to frontend',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className={"w-full min-h-screen bg-gray-50 p-4"}>
          {children}
        </main>
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
